language: elixir
elixir:
  - 1.7
  - 1.6
otp_release: '21.0'
services:
  - rabbitmq
env:
  - MIX_ENV=test
before_script:
  - sudo rabbitmqctl add_vhost rbt-test
  - sudo rabbitmqctl set_permissions -p rbt-test guest ".*" ".*" ".*"
script:
  - mix do deps.get, coveralls.travis
